# Generated by Django 6.0.3 on 2026-03-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HFModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=255, unique=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("downloads", models.IntegerField(default=0)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
